version: '3'
services:
  postgres:
    image: postgres:latest
    volumes:
      - postgres:/var/lib/postgresql
  redis:
    image: redis:latest
  cgwire:
    env_file:
      - .env
    build:
      context: .
      # dockerfile: Dockerfile_test
    volumes:
      - thumbnails:/opt/zou/zou/thumbnails
    ports:
      - "${HTTP_PORT}:80"
    depends_on:
      - postgres
      - redis

volumes:
  postgres:
  thumbnails:
