version: '3'
services:
  postgres:
    image: postgres:10.5
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis:latest
  cgwire:
    env_file:
      - .env
    image: cgwire:$ZOU_VERSION
    build:
      context: .
      # dockerfile: Dockerfile_test
    volumes:
      - thumbnails:/opt/zou/thumbnails
    ports:
      - "${HTTP_PORT}:80"
    depends_on:
      - postgres
      - redis

volumes:
  postgres:
  thumbnails:
