version: '3'
services:
  postgres:
    image: postgres:10.5
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always
  redis:
    image: redis:latest
    restart: always
  cgwire:
    restart: always
    env_file:
      - .env
    image: cgwire:z$ZOU_VERSION-k$KITSU_VERSION
    build:
      context: .
      args:
        KITSU_BRANCH: ${KITSU_VERSION}
        ZOU_VERSION: ${ZOU_VERSION}
        TINI_VERSION: ${TINI_VERSION}
      # dockerfile: Dockerfile_test
    volumes:
      - thumbnails:/opt/zou/thumbnails
    ports:
      - "${HTTP_PORT}:80"
    depends_on:
      - postgres
      - redis

volumes:
  postgres:
  thumbnails:
